[package]
name = "bioinformatics_algorithms"
version = "0.1.0"
authors = ["Luiz Irber <contact@luizirber.org>"]
edition = "2018"

[lib]
name = "bioinformatics_algorithms"

[dev-dependencies]
assert_cmd = "0.11.1"
predicates = "1.0.0"
tempfile = "3.0.7"

[dependencies]
rand = "0.6.5"
